### ISSUE TITLE
Hoe can I make Dynamic forms?

### ISSUE THREAD

**Issue by basketball-ico** [danvick/flutter_form_builder#104]

**Comment by danvick** [comment]
Hi @basketball-ico,
This is actually a good question because I've been thinking about having this as part of the package but haven't got around to doing it yet.
Just for clarification, by Dynamic forms, do you mean a way we can have dynamically added fields?
I could benefit from ideas and better yet, PRs ;-)

**Comment by jamiethain** [comment]
I am actually making a dynamic forms version from this version. It makes decisions about adding the forms and gets the properties from a Map.  

I stopped right now as this was a barrier to getting the basic demo going. 

Maybe we can work on it a bit.

**Comment by kalismeras61** [comment]
Hello any update for this? as @jamiethain says we can create forms from json map.

**Comment by beckojr** [comment]
I'm working on this in my app, the problem I'm facing is that once the dynamically is registered in the form, I can't find a way to unregister it even when I use `_fbKey.currentState.unregisterFieldKey(attr)` and there's no way for me to dispose the widget manually.

**Comment by awhitford** [comment]
Are there still any critical issues?  I am building dynamic forms with this library and don't seem to have any issues.

**Comment by nstrelow** [comment]
I need this 😁 
Following steps I am doing, which are not working:
1. Dynamically add fields with `attribute: 'something_$index'` <-- state is empty
2. _fbKey.currentState.save();  <-- state has map #1 of values

Now I am struggling to remove a dynamically added field:

3. _fbKey.currentState.unregisterFieldKey(attr) <-- does not work

Maybe because setState is not called?

`updateFormAttributeValue` works as expected.

![image](https://user-images.githubusercontent.com/1096841/86940947-a6956680-c143-11ea-839b-57a5b69f2050.png)

**Comment by nstrelow** [comment]
ungregisterFieldKey would have to be updated or a second option would need to be added:

@danvick What's your take on this?

```
void unregisterFieldKey(String attribute) {
      _value.remove(attribute);
      _fieldKeys.remove(attribute);
  }
```

Maybe needs setState as well

```
void unregisterFieldKey(String attribute) {
      setState(() {
      _value.remove(attribute);
      _fieldKeys.remove(attribute);
    });
  }
```

**Comment by mdeandrea-mrmilu** [comment]
Can be close this issue?

**Comment by deandreamatias** [comment]
Due to lack of response and an old error, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/danvick/flutter_form_builder/issues/new/choose)

Maybe can create a document issue for this
