### ISSUE TITLE
FormBuilderDateTimePicker onChanged callback returns incorrect date

### ISSUE THREAD

**Issue by opringle** [danvick/flutter_form_builder#164]
# Bug

When using the callback onChanged with FormBuilderDateTimePicker it returns dates from 1970, rather than the date the user selected!

# Steps to reproduce

- Create a form
- Add this form and use it

```
 FormBuilderDateTimePicker(
                initialDate: DateTime.now(),
                onChanged: (DateTime d){
                  print("SELECTED DATETIME: $d");
                },
                attribute: "startTime",
                inputType: InputType.both,
                format: DateFormat("EEEE MMM d kk:mm"),
                decoration:
                    InputDecoration(labelText: "Enter a time and view logs"),
              ),
```

**Comment by danvick** [comment]
Hi @opringle,
Thanks for bringing this to my attention. I'll test and work on a fix ASAP.

**Comment by danvick** [comment]
Seems this bug is caused by the underlying library, [datetime_picker_formfield](https://pub.dev/packages/datetime_picker_formfield), which when submitting it tries to parse the string in the `TextField` back to a `DateTime`. But since your `DateFormat` lacks the year field, it is substituted by 1970.

This issue has already [been reported](https://github.com/jifalops/datetime_picker_formfield/issues/64) in the library.

I'll try to do a workaround for the benefit of our library.

**Comment by danvick** [comment]
Hi @opringle,
Kindly check out v3.6.0. It contains a fix for this.
