### ISSUE TITLE
onSaved missing?

### ISSUE THREAD

**Issue by mathieurousseau** [danvick/flutter_form_builder#175]
I am usually using regular TextFormField.
I use onSaved to do some treatment only once when saved.

But on FormBuilder, I don't find the onSaved options which execute my code at all changes.

Any way to do like onSaved?

**Comment by danvick** [comment]
Hi @mathieurousseau,
Thanks for bringing this up. I'll be including it back shortly.
Here's a few things to note:
1. If all you need to do is to transform the data before saving you could use the `valueTransformer` function. A good use-case for this is to transform the value of a numeric TextField from string to a number.
2. Since we have a transformer when the `onSaved` will be included in the package, I wouldn't advise using it to make data transformations since the data will already me commited.

**Comment by mathieurousseau** [comment]
I am using valueTransformer for what i need but that does not feel right as i don’t transform.

More over, i need to retest but it seemed to be called twice on saving.

**Comment by danvick** [comment]
Fixed in v3.7.0. Feel free to reopen on case of any more feedback.
