### ISSUE TITLE
Request to migrate to AndroidX

### ISSUE THREAD

**Issue by yokiran** [danvick/flutter_form_builder#25]
Can this package and its dependencies be migrated to AndroidX please. 
By the way form builder is a great idea for a package.
Thanks

**Comment by danvick** [comment]
Working on it. Thanks for your contribution

**Comment by danvick** [comment]
Since this package (and it's dependancies to the best of my knowledge) doesn't directly interact with the underlying Android platform, I'm not sure I'm the one to make it compatible with AndroidX. Kindly try migrating your app to AndroidX and let me know of any breakages.

I've been able to migrate some of my apps without any issues.

Cheers!
