### ISSUE TITLE
Can't reset the form

### ISSUE THREAD

**Issue by DJRahim** [danvick/flutter_form_builder#263]
Hello, i have a FormBuilder() which contains : 

- FormBuilderChoiceChip()
- 2 FormBuilderTextField()
- and a Confirm and reset buttons

When i press the reset button, it reset only FormBuilderChoiceChip(), and when i removed it it works (resets the 2 FormBuilderTextFields).

I tried replacing FormBuilderChoiceChip() by a FormBuilderDropDown(), same thing.

flutter doctor : 

[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.44.2)
[✓] Connected device (1 available)
.

**Comment by leidig54** [comment]
Similar issues with reset(). It is either not working at all or working very intermittently. In my code only the DateTimePicker is consistently reset. But the other fields are ignored.

**Comment by danvick** [comment]
Hi all,
Thanks for your feedback.

We've always had issues to do with resetting FormBuilder. This is mainly due to:
1. How Flutter handles Form reset and 
2. How this package was implemented. 

I've made some progress in regard to this in the just-released v3.10.0. 
I'm also working on v4.0.0 of the package which is a complete re-write, [currently in alpha](https://pub.dev/packages/flutter_form_builder/versions/4.0.0-alpha.2) which aims to get rid of this issue among other structural ones.

Let's keep the feedback coming.
