### ISSUE TITLE
can we clear/reset a segmented control ?

### ISSUE THREAD

**Issue by SogoGolf** [danvick/flutter_form_builder#265]
hi, is it possible to completely 'reset' a segmentedcontrol ? By that i mean that every item in the segmented control becomes 'unselected'. Can this be done programmatically for individual segmented controls ?

**Comment by danvick** [comment]
I'm afraid that's not possible for SegmentedControl as it must have a value selected at all times.

**Comment by danvick** [comment]
Also, note that reset means return to the initial value and not clear contents.

**Comment by SogoGolf** [comment]
Thanks for quick reply. But the "form level" operation does clear all the selections? So I assume it must be possible on a (segmented)control by control basis?

**Comment by danvick** [comment]
There's a bit of an issue with resetting some controls mainly due to the implementation of the package - which is a known issue. 

I'm currently working on some patch to fix this but long-term, version 4  - which is in the works - is aimed at solving these issues long term.

Thanks for your patience.

**Comment by danvick** [comment]
Hi @SogoGolf, 
Kindly confirm that SegmentedControl can now be reset as of v3.10.0
