### ISSUE TITLE
Wrap label?

### ISSUE THREAD

**Issue by jaxnz** [danvick/flutter_form_builder#282]
I am building a web app, that requires a public form to be accessed by mobile. I have created a Textarea using FormBuilderTextField but my label is too long on mobile, and goes outside the field:

![image](https://user-images.githubusercontent.com/62976701/82175098-00896500-9927-11ea-94e0-d968ac96de43.png)

I have already shrunk the text using:

```
InputDecoration(
          labelStyle: TextStyle(fontSize: textSize),
),
```

I understand this may be a flaw in InputDecoration, but is this possible to fix?

**Comment by danvick** [comment]
Hi @jaxnz,
This is a sound suggestion, I've had issues with this myself.

However, this would not be possible without overriding the whole `InputDecoration` class. This is because `overflow: TextOverflow.ellipsis` is hard-coded in `InputDecoration` class.

The only suggestion I can think of at this time is making your own `Text` label, and leave the `decoration` option empty. Like so:
```dart
Text(
  "What are your first impressions of our center?",
  style: Theme.of(context).inputDecorationTheme.labelStyle,
),
FormBuilderTextField(
  attribute: "text_field",
),
```

It will not work exactly as the InputDecoration label but at least the whole label will be visible.
