### ISSUE TITLE
Build Flutter error with example

### ISSUE THREAD

**Issue by ankitbhattarai** [danvick/flutter_form_builder#294]
I build a source example to a device with Android Studio. But an error occurred.
![image](https://user-images.githubusercontent.com/46476156/83222893-333e2380-a199-11ea-80f3-db3735814e4b.png)

**Comment by danvick** [comment]
Hi @ankitbhattarai,
I think this is caused by a feature introduced in Flutter 1.17 and consequently version 1.3.0 of the country_pickers package on which the package depends.
There may be two possible solutions to this:
1. Restrict your dependency of `country_pickers` to version 1.2.1 using `dependency_overrides` within your `pubspec.yaml `
2. Upgrade your Flutter version to the newest stable version 1.17
