### ISSUE TITLE
Unable to set the initial values of the fields

### ISSUE THREAD

**Issue by DinoSane** [danvick/flutter_form_builder#3]
I've tried the simplest FormBuilder to read and write SharedPreferences.

TextFormField(initialValue: _name ) shows as it should

FormBuilderInput.textField(
                    type: FormBuilderInput.TYPE_TEXT,
                    attribute: "name",
                    value: _name,
                    label: "Name:",
                  )

Does not!

**Comment by danvick** [comment]
Hello @DinoSane,
I'm unable to reproduce your issue, could you kindly elaborate on the issue, more code could be helpful.

**Comment by DinoSane** [comment]
I created a simple project to ilustrate the problem 
can you clone it?

git clone git@bitbucket.org:dinosane/form_builder.git

thanks in advance.

**Comment by danvick** [comment]
Please note that your string is fetched from SharedPreferences after the form is already built since the fetching is asyncronous. See code below and the corresponding console output:

`
class _FailingPageState extends State<FailingPage> {
  String _aStringValue = '';

  @override
  void initState() {
    _loadVals();
    super.initState();
  }

  //Loading counter value on start
  _loadVals() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    prefs.setString('aStringValue', 'My string value');
    _aStringValue = prefs.getString('aStringValue');
    print("After fetch '$_aStringValue'");
  }

  @override
  Widget build(BuildContext context) {
    print("During build '$_aStringValue'");

    return SharedScaffold(
      titulo: 'Failing',
      body: Padding(
        padding: EdgeInsets.all(20.0),
        child: Padding(
          padding: EdgeInsets.all(20.0),
          child: FormBuilder(
            context,
            autovalidate: true,
            controls: [
              FormBuilderInput.textField(
                type: FormBuilderInput.TYPE_TEXT,
                attribute: "aStringValue",
                value: _aStringValue,
                label: "Any Value:",
              )
            ],
            onChanged: () async {},
            onSubmit: (formValue) async {
              if (formValue != null) {
                print(formValue);
                final prefs = await SharedPreferences.getInstance();
                prefs.setString('aStringValue', formValue['aStringValue']);
              } else {
                print("Form invalid");
              }
            },
          ),
        ),
      ),
    );
  }
}
`

Console:
`
Performing hot restart...
Syncing files to device Android SDK built for x86...
Restarted application in 1,699ms.
I/flutter ( 4934): During build ''
I/flutter ( 4934): After fetch 'My string value'
`

I'd advise declaring the form within a `FutureBuilder` or a similar implementation

**Comment by DinoSane** [comment]
You are correct!

Using a FutureBuilder solve the problem.

I though setting the value inside a setState was suffice, but as you pointed, it doesn't.
Thanks.

**Comment by DinoSane** [comment]
I forgot to say: great job! :-)

**Comment by danvick** [comment]
You're welcome @DinoSane. Thank you.

Also note that you're not really required to use `setState()` when setting a value within `initState()`
