### ISSUE TITLE
Trigger save from outside form

### ISSUE THREAD

**Issue by jasonlaw** [danvick/flutter_form_builder#32]
Is it possible to trigger the save action from outside of the form? I would like to place a save button/icon on the App bar, but I am not sure how to trigger the form save.

Thanks in advance.

**Comment by danvick** [comment]
Hi @jasonlaw,
I think the easiest option is to allow passing in the `GlobalKey<FormState>` so that one has the handle to the form itself then do away with the submit and reset buttons. 

This will make it easier for the developer to have control over submitting/resetting and putting a loader.

What do you think?

**Comment by jasonlaw** [comment]
I think that is a great idea, thank you very much!
