### ISSUE TITLE
How to persist values

### ISSUE THREAD

**Issue by danielwalczak** [danvick/flutter_form_builder#351]
I have multi step form implemented with PageView.builder, but the issue is that the values are removed when I moved between pages because the controllers are disposed. What is the best way to persist values?

**Comment by danielwalczak** [comment]
I think its the issue with TextField initState

```
_initialValue = widget.initialValue ??
        (_formState.initialValue.containsKey(widget.attribute)
            ? _formState.initialValue[widget.attribute]
            : null);
```
It should also consider that formState have saved value using .saveAndValidate(), so it would work after the textField was disposed and render again.

**Comment by danvick** [comment]
Using FormBuilder across multiple Pages on PageView will bring a number of unexpected behaviors, none of which has to do with FormBuilder directly and how it's expected to be used.

I think this is because PageView navigates across different routes, each of which has a different context. It's almost like using one Widget across several Routes.

Consider referring to #222.
