### ISSUE TITLE
Flutter beta 1.22.0-12.1.pre - compile error

### ISSUE THREAD

**Issue by slavap** [danvick/flutter_form_builder#465]
```
/C:/Programs/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.14.0-alpha.3/lib/src/form_builder_custom_field.dart:96:40: Error: The getter 'autovalidate' isn't defined for the class 'FormField<T>'.
 - 'FormField' is from 'package:flutter/src/widgets/form.dart' ('/C:/Programs/flutter/packages/flutter/lib/src/widgets/form.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'autovalidate'.
        autovalidate: widget.formField.autovalidate,
                                       ^^^^^^^^^^^^
```

For 3.13.5 it is even worse:

```
/c:/Programs/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.5/lib/src/fields/form_builder_range_slider.dart:21:9: Error: Type 'RangeSemanticFormatterCallback' not found.
  final RangeSemanticFormatterCallback semanticFormatterCallback;
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/c:/Programs/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.5/lib/src/fields/form_builder_range_slider.dart:21:9: Error: 'RangeSemanticFormatterCallback' isn't a type.
  final RangeSemanticFormatterCallback semanticFormatterCallback;
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/c:/Programs/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.5/lib/src/form_builder_custom_field.dart:96:40: Error: The getter 'autovalidate' isn't defined for the class 'FormField<T>'.
 - 'FormField' is from 'package:flutter/src/widgets/form.dart' ('/c:/Programs/flutter/packages/flutter/lib/src/widgets/form.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'autovalidate'.
        autovalidate: widget.formField.autovalidate,
                                       ^^^^^^^^^^^^
```

**Comment by knaeckeKami** [comment]
I fixed in it my fork, you can use it via

  flutter_form_builder:
    git:
      url: https://github.com/knaeckeKami/flutter_form_builder.git
      ref: v3.14.0-alpha.2-fix

I would open a PR, but I'm not sure against which branch I should open it, and the alpha.3 version seems to not be tagged, so I used the alpha.2 tag. I'm happy to follow up with a PR.

**Comment by kuhnroyal** [comment]
This is a breaking change, I don't think there is a backwards compatible way to handle this. Maybe with an extension on FormField?

**Comment by skyeskie** [comment]
It looks like they are adding back in at least a (deprecated) getter so it'll compile. However, I'm not sure how quickly it'll go through the various Flutter versions.

So it looks like `autovalidateMode` was added (in 1.21.x) present before `autovalidate` was removed (in 1.22.x). We could just fully switch that line to using:
` autovalidateMode: widget.formField.autovalidateMode,`
- All state is already stored by the underlying FormField
- As of 1.21.x, the only guaranteed state in `FormField` is from `autovalidateMode`
  - If `autovalidate` is used in creating the `FormField`, `autovalidateMode` is also set
  - If `autovalidateMode` is used in creating the `FormField`, `autovalidate` is left to its default value (`false`)
  - Ref: [FormField constructor code in 1.21-candidate.10](https://github.com/flutter/flutter/blob/7a50c0fcc506dc018ee53ee84770259dc7a97f8c/packages/flutter/lib/src/widgets/form.dart#L316-L334)
- There'd be no way to utilize `AutovalidateMode.onUserInteraction`, since that's new middle-ground state

**Comment by kuhnroyal** [comment]
> It looks like they are adding back in at least a (deprecated) getter so it'll compile. However, I'm not sure how quickly it'll go through the various Flutter versions.
Do you have an issue number for this?

**Comment by skyeskie** [comment]
No issue, but (draft) PR is https://github.com/flutter/flutter/pull/66267

**Comment by kuhnroyal** [comment]
https://github.com/flutter/flutter/issues/66940 is now marked for cherry pick into Flutter 1.22 and should solve this.

**Comment by skyeskie** [comment]
@kuhnroyal
While the property is being added back in to not break things, it's still being deprecated.
```dart
  @Deprecated(
    'Use autoValidateMode parameter which provides more specific '
    'behavior related to auto validation. '
    'This feature was deprecated after v1.19.0.'
  )
  final bool autovalidate;
```

So should probably still go ahead with the fix suggested above and switch to `autovalidateMode`

**Comment by kuhnroyal** [comment]
@skyeskie That is correct, but for now I am looking just for a library version that compiles with 1.22.0

**Comment by danvick** [comment]
v3.14.0 compiles with Flutter 1.22.*

**Comment by shadyshrif** [comment]
> Proposed fix:
> autovalidate: widget.formField.autovalidateMode == AutovalidateMode.always,

this is the correct answer
