### ISSUE TITLE
Show/Hide functionality for password field

### ISSUE THREAD

**Issue by pavankumarkatakam** [danvick/flutter_form_builder#48]
It a basic need for almost every password should have hide and show button with an eye icon. we have keep in flutter with stack widgets i think. i will try it meanwhile anybody can do a pull request.

**Comment by danvick** [comment]
Hi @pavankumarkatakam, 

I'm not sure of the necessity of baking this into the package especially because of version 3.0.0 the package has a more configurable UI structure and one can create their own implementation of a toggle. The problem with including our own toggler is that we'll have to decide how it looks which may not be preferable to all.

For instance you can create a `Row` with a button next to your `FormBuilderTextField` that will toggle the `obscureText` attribute. Like so:
```dart
Row(
    children: <Widget>[
        Expanded(
            child: FormBuilderTextField(
                attribute: "password",
                obscureText: _showPassword,
                decoration: InputDecoration(labelText: "Password"),
           ),
        ),
        IconButton(
            icon: Icon(Icons.remove_red_eye),
            onPressed: (){
                 setState(() {
                   _showPassword = !_showPassword;
                });
            },
        )
    ],
),
```

If you still think this will make a good addition to the package let's engage further and see how it can be done.
