### ISSUE TITLE
Phone field validation might be wrong

### ISSUE THREAD

**Issue by shunei4517** [danvick/flutter_form_builder#486]
Hello, I'm having issue in PhoneNumber field.
I did not have any problem while using v3.13.2, but when I updated to v3.14.0, I got this problem.
The problem is 
- Validation fails in valid phoneNumber(+12125550162, +12125550160 etc)

![スクリーンショット 2020-10-04 12 06 33](https://user-images.githubusercontent.com/52183552/95006056-d832a680-063a-11eb-975b-df03bbc59754.png)

Here is my code
```dart
FormBuilderPhoneField(
  attribute: 'phoneNumber',
  defaultSelectedCountryIsoCode: 'JP',
  decoration: const InputDecoration(
    labelText: 'Phone',
    errorMaxLines: 1,
  ),
  priorityListByIsoCode: const ['JP', 'US'],
  validators: [
    FormBuilderValidators.required(errorText: emptyErrorMessage),
    FormBuilderValidators.numeric(errorText: phoneErrorMessage),
  ],
  onChanged: (dynamic value) {
    context
      .read<PhoneRegistrationStateNotifier>()
      .updatePhoneNumber(value, 'phoneNumber');
  }
),

// context.read.updatePhoneNumber
void updatePhoneNumber(dynamic number, String attribute) {
  final validationResult = !state
    .formBuilderKey.currentState.fields[attribute].currentState
    .validate();
  phoneNumber = number.toString();
  hasError = validationResult;
}
```

I think the number I am using is valid number, but I can't figure out what is wrong with this input.
My error messages are Japanese, so actually English message is not going to be displayed, and this means the validation error is not from my validator.
Am I missing something?

**Comment by danvick** [comment]
@tejisav-fandemand Your PR to PhoneField seemed to include phone number validation which causes errors for users in some countries.

The reason why we intentionally didn't include phone number validation as part of the package is because this is a complex affair that is not standard all over the world. We also have `FormFieldValidator`s for this purpose.

We could either remove phone validation all together or make it optional with an attrubite to turn it on whenever one is sure they want to use our implementation of it.

**Comment by tejisav-fandemand** [comment]
@danvick We can definitely make it optional but the main problem is:-
https://github.com/danvick/flutter_form_builder/blob/master/lib/src/fields/form_builder_phone_field.dart#L139
The same parser used for validation is used to separate country code and number so that we can set initialValue to the fields. The only way to solve this is using a map for storing country code and number separately instead of a single fullNumber string.

**Comment by deandreamatias** [comment]
This still a issue?

**Comment by deandreamatias** [comment]
Due to lack of response and an old error, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/danvick/flutter_form_builder/issues/new/choose)
