### ISSUE TITLE
Custom design not possible

### ISSUE THREAD

**Issue by pavankumarkatakam** [danvick/flutter_form_builder#49]
At present, the controls property is typed as `List<FormBuilderInput>` instead of `List<Widget>`, so that we are unable to add Gap between forms, or inserting Sub headings or even custom desing like keeping two form fields in a row.

**Comment by danvick** [comment]
This is being addressed in the next version - 3.0.0 - which is currently in beta. Feel free to have a go at it from pub - [https://pub.dartlang.org/packages/flutter_form_builder/versions/3.0.0-beta.9](https://pub.dartlang.org/packages/flutter_form_builder/versions/3.0.0-beta.9).

There are people who have started using it already in their projects since we are not expecting much API changes when version 3 will be officially released.

Your feedback will be much appreciated.
