### ISSUE TITLE
[Question] FormBuilderFilterChip change label style on selected

### ISSUE THREAD

**Issue by JaviCore** [danvick/flutter_form_builder#503]
Hello there,
I have tried to look for an option like this but it seems I can only change the chip's fillcolor. Did I miss it or is just simply not supported as of now? If not is this something planned in the future?

Thanks

**Comment by danvick** [comment]
Hi, @JaviCore 

Since our FormBuilderFilterChip field uses Flutter's own FilterChip, we are only limited to the options given by the dependent widget. 

As for now, Flutter's `FilterChip` doesn't allow us to change the label style of a selected chip. 

In Material's `ThemeData.chipTheme` class there's an option named `secondaryLabelStyle` which should affect the label style of selected Chips but this somehow doesn't work for `FilterChip`s but it does for `ChoiceChip`s.

**Comment by JaviCore** [comment]
@danvick Thanks for the reply. I'll keep it in mind and just wait till a future update allows you to do that :)

**Comment by awhitford** [comment]
@JaviCore You could report an issue with [Flutter](https://github.com/flutter/flutter/issues).

**Comment by Natnaelk** [comment]
I'm facing the same issue. Is there any solution?
