### ISSUE TITLE
Please remove 2 of Version 4 Branch assertions

### ISSUE THREAD

**Issue by danielweil** [danvick/flutter_form_builder#566]
Hey, 

In the version 4 branch, it was added a couple of assertions that do not make any sense.
I use the package exclusively for a dynamic form, and when I dynamically change what fields are in the form, I rebuilt the page in the pageview.

With these assertions, Everytime the fields in the form change, an assertion error is triggered.
Is it possible to take these down? I use the version 4 branch for a couple of new fixes, but if these assertions continue, I won't be able to use it. These two methods modifies the value for the field key in the fields map. It does not duplicate it.

![image](https://user-images.githubusercontent.com/44274213/98981403-a72c7800-24fc-11eb-9806-dc4cf45a5884.png)

**Comment by awhitford** [comment]
@danielweil We appreciate your feedback!

These assertions were added because it addressed a TODO for ensuring that Field Names are unique.  You can see that what it is saying is that when you register field, it must be for a new name -- not one that already exists.  It is designed to prevent/warn you when you have two or more fields using the same name.  That scenario is illegal and confusing.

So having said that, what are you trying to do exactly?  Dynamic fields are not a problem.  However, each dynamic field does require a unique name.  The expectation is that the old field is disposed (which unregisters) before creating a new field for the same name.  My suspicion is that you may have a leak.

Are you able to share some sample code that exhibits the problem?

**Comment by danielweil** [comment]
Hey Antonio, the code is very complicated to share it like this. You would
need the backend as well.

I don't see the need to disposing a field to have it appear again.

There isn't anything to do?

Anthony Whitford <notifications@github.com> escreveu no dia sábado,
14/11/2020 à(s) 01:00:

**Comment by awhitford** [comment]
Imagine someone creates two fields with the same name -- one field is a Slider, and the other is a Text field.  _Should that work?_  No.  The assertion helps point out that the situation is _invalid_.  (It is often a copy/paste error where someone forgot to adjust the name attribute to make it unique.)

In your case, if you are intentionally replacing a field for name X, the widget lifecycle needs to be:
1. create X (registers X)
2. dispose X (unregisters X)
3. create X' (registers X)
4. dispose X' (unregisters X)

If you do this, then there will be no assertion because there will be no duplicate field registration.  Note that you may not need to manually call `dispose` as Flutter often takes care of that.

However, if the lifecycle is jumbled and executed incorrectly like:
1. create X (registers X)
2. create X' (registers X) 🐞 -- _duplicate registration for X_
3. dispose X (unregisters X) 🐞 -- _unregisters X', not X_
4. dispose X' (unregisters X) 🐞 -- _duplicate unregistration for X_

This will trigger the assertion and highlight a bug in the use of the framework.

I do not need to see your actual code, but if you could illustrate what you are doing in some sample code that exhibits the problem, then I could likely better explain how to adjust the code to comply.  (This is the same expectation that core Flutter issues demand.)

**Comment by awhitford** [comment]
I created some sample code that creates two fields with the same name, but not at the same time -- which should be legal.  It appears that I am able to reproduce @danielweil's issue.  I am surprised to see Flutter initialize a new widget before disposing of the old widget, so my simple example is doing what is unexpected.

Please note that this corrupts FormBuilder's `_fields` variable -- the field with the duplicate name has been registered twice and then prematurely removed.  This breaks the `FormBuilder.patchValue` method.  This is precisely the kind of thing that I was worried about.

Researching.

**Comment by awhitford** [comment]
It appears that this observation has been raised: https://github.com/flutter/flutter/issues/67110
However, no real resolution.

As a result, I relaxed the assertion.  Note that it will still emit a warning in Debug mode only to highlight the scenario where this is unintentional.  Also, I fixed the code so that `_fields` stays valid.

**Comment by danielweil** [comment]
Thank you very much. I will check if I can adjust the code in order to best make my lifecycle works. But thanks anyway!
