### ISSUE TITLE
FocusNode leak

### ISSUE THREAD

**Issue by awhitford** [danvick/flutter_form_builder#578]
These look like they are leaking `FocusNode` instances:

https://github.com/danvick/flutter_form_builder/blob/a94a3ccf04c7b7a25b222a9c2c89c6c12cea1644/lib/src/fields/form_builder_color_picker.dart#L214

https://github.com/danvick/flutter_form_builder/blob/a94a3ccf04c7b7a25b222a9c2c89c6c12cea1644/lib/src/fields/form_builder_date_range_picker.dart#L247-L249

I'm unclear on what these are doing, why they exist, and how to _fix_ it.

Note that I'm not aware of a significant runtime issue.  I am merely worried that this isn't consistent with Flutter's [FocusNode lifecycle](https://api.flutter.dev/flutter/widgets/FocusNode-class.html#lifecycle):
> A stateful widget that owns a focus scope node must call dispose from its `State.dispose` method.

**Comment by danvick** [comment]
I was using those as a hack to hide the keyboard when it appears when you tap the `TextField`s on ColorPicker and DateRangePicker since the keyboard isn't needed in both.

I later discovered that setting `readOnly: false` in the `TextField` would ensure the keyboard doesn't even pop up. I think these lines could now be safely removed.

**Comment by danvick** [comment]
Closed by https://github.com/danvick/flutter_form_builder/commit/ddfb895ec5e20aaf6e32d6fd5e0b8e9f88efbcdc
