### ISSUE TITLE
A GlobalKey was used multiple times inside one widget's child list.

### ISSUE THREAD

**Issue by danielweil** [danvick/flutter_form_builder#590]
Hello Again!

With the new version updates (I was previously on pre-6), I began experiencing two different issues. I am not sure they are related.
Let me explain what is my use case scenario. I have a widget that is a modal that contains a form (FormBuilder) inside it. Inside the FormBuilder, I have a PageView with several ListViews, and I can dynamically add new pages. 

I use one GlobalKey per FormBuilder, and previously, I had no issue with the GlobalKey, but now, when I close the modal, and try to open it again, it gives me the following error:
"A GlobalKey was used multiple times inside one widget's child list."

The widget only disposes when I move within a 3 page distance. So I don't know what could have changed. 
For now, I am reinitializing the global key whenever I close the modal, which I am not sure is the ideal way to go.

The second issue is a recurrent one, which I already created an issue previously, and got fixed. But now with the new version, it keeps happening again. When I close the modal, and open it again, it gives me this following exception:

![image](https://user-images.githubusercontent.com/44274213/100155467-16538600-2e86-11eb-9b8f-ea978ad53019.png)

Curious thing, when I reinitialize the FormBuilder key, it stops giving the second error as well.

Sincerely,
Daniel

**Comment by awhitford** [comment]
I suspect that you've got issues managing the FormBuilder key.  That assertion would fire if you are disposing of a field twice -- that seems illogical, and is likely due to redundant code.

I doubt that this is truly a `flutter_form_builder` issue.  If you can boil down the problem into a reproducible test case, then I'd suggest tweaking the code to use the out-of-the-box `Form` and _Fields_ (no FFB), and the assertion will go away but I bet you still have the other issue.  If OOTB works, but FFB does not, then I'd also suspect FFB is doing something wrong.

**Comment by danielweil** [comment]
Was able to fix it, Not sure what fixed it though
