### ISSUE TITLE
FormBuilderChipsInput 4.0.0+ focus problem

### ISSUE THREAD

**Issue by ydenizs** [danvick/flutter_form_builder#612]
After adding first chip, it's impossible to add new ones without losing and regaining focus. Works on version 3.14.1 without any problem. Even example chip input code in the github is not working. My version is 4.0.2.

Thank you.

**Comment by danielweil** [comment]
I am also having this problem!

**Comment by ProfHercules** [comment]
I have determined that this problem exists on both iOS and Android.
The problem comes from the flutter_chips_input packages, I think.

On Line 247 in lib/src/chips_input.dart (in flutter_chips_input)
`widget.onChanged(_chips.toList(growable: false));`
is called. If this line is commented out, the 'losing focus' issue disappears - but you lose the ability to use the onChanged callback.

I've not had time to delve deeper into this, I may also be way off the mark!
Will report back if I find anything more.

**Comment by awhitford** [comment]
I think I fixed this with PR #640.  I think the `key` attribute was forcing a tree rebuild which was messing with the focus.
