### ISSUE TITLE
my app dpendeds on flutter_form_builder ^4.0.2 and intl ^0.17.0-nullsafety.2, version solving failed.

### ISSUE THREAD

**Issue by prakash-indorkar** [danvick/flutter_form_builder#634]
Because flutter_form_builder 4.0.2 depends on intl ^0.16.1 and no versions of flutter_form_builder match >4.0.2 <5.0.0, flutter_form_builder ^4.0.2 requires intl ^0.16.1.

Hi.. could please apply this fix. Thanks & regards

**Comment by ProfHercules** [comment]
I believe intl 0.17.0-nullsafety.2 is not yet a stable release, since null safety is also not yet in stable - therefore I don't think changing the package directly is the right approach for now.

That being said, I think you could use `dependency_overrides` to achieve the desired outcome.
Including something like:
```
dependency_overrides:
  intl: ^0.17.0-nullsafety.2
```
in your pubspec.yaml should solve the problem.

You can learn more [in the Dart docs](https://dart.dev/tools/pub/dependencies#dependency-overrides).

**Comment by prakash-indorkar** [comment]
It is still giving warning.. Not able to build with --release

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by luxosrdc** [comment]
same issue

**Comment by kinhvanuq** [comment]
Same issue. Not sure how can I use flutter_form_builder again?

**Comment by danvick** [comment]
Hi @minhluan1590, @prakash-indorkar et al.

Sorry for the inconvenience. We however had nothing to do with the regression. 

`flutter_localizations` - which comes from the Flutter SDK - seems to be the offending dependency. The latest versions of the dependency seem to depend on a pre-release version of `intl` which seems to cause the issue. 
In normal circumstances, @ProfHercules solution - with `dependency` - would work and no more issues would be faced.

Since, as reported, this issue causes your apps not to build in release mode, more investigations need to be done.

Which versions of Flutter are you building on? 

And does overriding with `intl: ^0.16.1` work?

**Comment by minhluan1590** [comment]
Dear Mr. Danvick Miller,

 

I am not sure about the release branch of flutter, but I am using Dev branch, to be able to have Desktop and Web platform.

 

Yes, today I tried with overriding dependency and it works (even there is some warning). I think it’s good for now.

 

Thank you for your email.

 

Best regards,

Luan Pham

**Comment by prakash-indorkar** [comment]
Same for me as well.

I'm using 
dependency_overrides:
  intl: ^0.17.0-nullsafety.2

It is able to build but with a warning about the override. 

Maybe in the future, it must need to be revisited, so we no longer have to override.

Regards, Prakash

**Comment by joeyyy688** [comment]
dependency_overrides:
   intl: ^0.17.0-nullsafety.2
did this but the error stil coming as 
Because myapp depends on dependency_overrides from unknown source "intl", version solving failed.
pub get failed (1; Because myapp depends on dependency_overrides from unknown source "intl", version solving failed.)

**Comment by ShadowOfThePenguin** [comment]
@joeyyy688 that problem can be caused by the spacing in the yaml file, make sure there are no tabs before 'dependency_overrides:' and a single tab before 'intl: ^0.17.0-nullsafety.2'. Otherwise it thinks you want to download the package 'dependency_overrides' from the source ''intl: ^0.17.0-nullsafety.2'

**Comment by faithoflifedev** [comment]
The following worked for me:
dependencies:
  intl: ^0.16.1
dependency_overrides:
  intl: ^0.17.0-nullsafety.2

However I was getting the error for debug builds, I haven't tried a release build

**Comment by deandreamatias** [comment]
This still a issue?

**Comment by deandreamatias** [comment]
Solved with new versions

**Comment by joeyyy688** [comment]
Nope, built my own package to solve the issue I was facing. Secondly, that
package was too buggy.
