### ISSUE TITLE
Break into smaller packages

### ISSUE THREAD

**Issue by gilmarsquinelato** [danvick/flutter_form_builder#717]
Firstly, thank you for this great library!

I'd like to suggest to break the custom fields into smaller separate packages, keeping into the main package only the flutter builtin fields.
The reason is that I saw a few issues related to these custom fields, and some others breaking builds.
An example is the date range picker, it was deprecated and now it's supported in the Flutter framework, the dev channel build is breaking. In that case, if it was a separate package, being optional, we wouldn't have this problem.

This would make the main repo smaller, with the issues being better addressed into the right repositories.

Hope this helps 😄

**Comment by masseelch** [comment]
I totally agree to this.

**Comment by AlBlanc** [comment]
This is what I started to do (just removing extra inputs for the moment, I'll try to create the inputs into extra packages asap)

https://github.com/danvick/flutter_form_builder/issues/729#issuecomment-791328663

**Comment by gilmarsquinelato** [comment]
Recently I decided to create another library for building forms in flutter.
It's in very early stages yet, but sounds promising [https://github.com/gilmarsquinelato/FormKit_flutter](https://github.com/gilmarsquinelato/FormKit_flutter)

**Comment by danvick** [comment]
This is a great idea @gilmarsquinelato and  we've done a bit of that: we have separate  packages for  [form_builder_map_field](https://pub.dev/packages/form_builder_map_field), [form_builder_image_picker](https://pub.dev/packages/form_builder_image_picker), [form_builder_phone_field](https://pub.dev/packages/form_builder_phone_field), [form_builder_file_picker](https://pub.dev/packages/form_builder_file_picker) in separate packages already. We did this until we had dependencies that we're sure are being actively maintained and also support most platforms. 

I'm happy that the Flutter team is including some of these functionalities that we had to depend on external libraries for into the framework repo - like the date range picker case. This way we are sure that the code we are depending on is clean and well maintained.

You'll however come to the realization - as I did - that breaking up an opensource package into multiple repositories exponentially multiplies the maintenance cost.

I would still however consider moving some of the packages that aren't compatible with Flutter 2 to separate packages. Or remove them from the package altogether since the package allows creating custom fields.

**Comment by gilmarsquinelato** [comment]
Thanks @danvick!

I totally agree with you about breaking into smaller packages!
With FormKit my idea is to support only the builtin widgets in the core package, and then add separate packages under demand, as the users begin requesting them.
It's sad that Flutter is so verbose to create a form, my objective in FormKit is to remove all this verbosity and make flutter forms fun to work with 😄

**Comment by WilliamCunhaCardoso** [comment]
Saw the owner divided the package in three ones. Maybe more separated packages can come. Closing the issue. More suggestions about how this segregation can be done, please file a new issue.
