### ISSUE TITLE
Multi language support

### ISSUE THREAD

**Issue by jasonlaw** [danvick/flutter_form_builder#72]
Referring to issue #17, may I know any progress on the multi language support?
Thank you very much!

**Comment by danvick** [comment]
Hi @jasonlaw,
I haven't been able to do this. Kindly note that the issue was raised before version 3 which allowed one to create your own `InputDecoration` and `errorText` option for `FormBuilderValidators` where one can add their own labels and get custom error message in whichever language.

Do you think this is still required? And where exactly do we need to 'internationalize'?

**Comment by jasonlaw** [comment]
Hi 
I am actually referring to FormFieldValidator. There are some very useful built in validator such as required field. I certainly do not want to reinvent the wheel. 
Thank you for this great library.
