### ISSUE TITLE
Because flutter_form_builder >=3.7.3 depends on intl ^0.16.1 and every version of flutter_localizations from sdk depends on intl 0.17.0, flutter_form_builder >=3.7.3 is incompatible with flutter_localizations from sdk.

### ISSUE THREAD

**Issue by Shiba-Kar** [danvick/flutter_form_builder#728]
```
[√] Flutter (Channel stable, 2.0.0, on Microsoft Windows [Version 10.0.19042.844], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.4)   
[√] Android Studio (version 4.1.0)
[√] VS Code, 64-bit edition (version 1.53.2)
[√] Connected device (4 available) 
```

**Comment by Iccr** [comment]
I got away  from this with dependency overrides in pubspec.yaml:
`dependency_overrides:`
 intl: ^0.17.0-nullsafety.2`

**Comment by ebelevics** [comment]
After adding intl: ^0.17.0-nullsafety.2 I get:

Because no versions of google_fonts match >2.0.0 <3.0.0 and google_fonts 2.0.0 depends on http ^0.13.0, google_fonts ^2.0.0 requires http ^0.13.0.

Because vin_decoder >=0.1.3 <0.2.0-nullsafety depends on http ^0.12.2 and vin_decoder >=0.1.2 <0.1.3 depends on http ^0.12.1, vin_decoder >=0.1.2 <0.2.0-nullsafety requires http ^0.12.1.

Thus, google_fonts ^2.0.0 is incompatible with vin_decoder >=0.1.2 <0.2.0-nullsafety.

And because flutter_form_builder >=4.0.0-alpha.3 depends on validators ^2.0.1 which depends on vin_decoder ^0.1.2, google_fonts ^2.0.0 is incompatible with flutter_form_builder >=4.0.0-alpha.3.

**Comment by Iccr** [comment]
> After adding intl: ^0.17.0-nullsafety.2 I get:
> 
> > ```
> > Because no versions of google_fonts match >2.0.0 <3.0.0 and google_fonts 2.0.0 depends on http ^0.13.0, google_fonts ^2.0.0 >requires http ^0.13.0.
> > 
> > Because vin_decoder >=0.1.3 <0.2.0-nullsafety depends on http ^0.12.2 and vin_decoder >=0.1.2 <0.1.3 depends on HTTP >^0.12.1, vin_decoder >=0.1.2 <0.2.0-nullsafety requires http ^0.12.1.
> > 
> > Thus, google_fonts ^2.0.0 is incompatible with vin_decoder >=0.1.2 <0.2.0-nullsafety.
> > 
> > And because flutter_form_builder >=4.0.0-alpha.3 depends on validators ^2.0.1 which depends on vin_decoder ^0.1.2, >google_fonts ^2.0.0 is incompatible with flutter_form_builder >=4.0.0-alpha.3.
> > ```

 looks like nullsaftey is giving you the problem. I think, [here](https://github.com/danvick/flutter_form_builder/issues/721) is better discussion about this.

**Comment by AlBlanc** [comment]
https://github.com/danvick/flutter_form_builder/issues/729#issuecomment-791328663

**Comment by alexmarkley** [comment]
I just donated to the developer @danvick with a request to prioritize Flutter 2.0.0 support. I would encourage anyone depending on this package to do the same! https://www.buymeacoffee.com/wb5M9y2Sz/c/1126129

**Comment by deandreamatias** [comment]
This bug exists and is tracked here #721. There have a discussion about this and possible solutions
