### ISSUE TITLE
How to set initial value in FormBuilderChoiceChip?? (One chip pre selected)

### ISSUE THREAD

**Issue by rmControls** [danvick/flutter_form_builder#833]
On screen load I want to make one specific chip pre-selected how to achieve it??

I tried with` initialValue = 2` and it is not working....

**Comment by ShadyZekry** [comment]
hi @rmControls,

I just tried this case, and It's working fine,
I guess that it's not working for you because you are addressing the chip value, and `initValue` is actually addressing the `int` value of the chip.
```Dart
 FormBuilderChoiceChip<int>(
  name: 'test_name',
  initialValue: 8,
  options: const [
    FormBuilderFieldOption(value: 8),
    FormBuilderFieldOption(value: 4),
    FormBuilderFieldOption(value: 15),
  ],
}
```

![image](https://user-images.githubusercontent.com/42680354/122502883-bfff8d80-cff7-11eb-985e-5de7f6fdea5f.png)


If that wasn't the right solution, please provide a code-snippet that produces the issue.

**Comment by rmControls** [comment]
Thank you for the example... it was my fault... I assumed that initialvalue is an index of options... its actually a value of one of the option.... 

can you also help me to resolve my other question... [https://github.com/danvick/flutter_form_builder/issues/832](https://github.com/danvick/flutter_form_builder/issues/832)??
