### ISSUE TITLE
RGB only color picker

### ISSUE THREAD

**Issue by wkrasnicki** [danvick/flutter_form_builder#918]
Hi, is it possible to use the default color picker field, but without the alpha channel? If not, would it be possible to add it?

**Comment by danvick** [comment]
Hi @wkrasnicki,
Kindly note that [form_builder_extra_fields](https://pub.dev/packages/form_builder_extra_fields) makes use of [flutter_colorpicker](https://pub.dev/packages/flutter_colorpicker) which has different modes to choose from.

Since flutter_form_builder [allows you to convert any widget into a FormBuilderField](https://github.com/danvick/flutter_form_builder/blob/master/packages/flutter_form_builder/README.md#building-your-own-custom-field), I'd suggest you make use of this feature if you can't find a field that you prefer in the packages provided.

The reason for this is that there are literally thousands of widgets we could include in the package, which would be a lot of work - hence the API to make any field work with FormBuilder.
